name: arabic_reader
description: a simple application that focuses on the beauty of the Liturgical life of the Coptic Orthodox Church through its hymns 
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:

  cupertino_icons: ^0.1.2
  cloud_firestore: ^0.11.0+2
  provider: ^2.0.1
  shared_preferences: ^0.5.2

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
   

flutter:

  uses-material-design: true

  fonts:
    - family: ArialCoptic
      fonts:
        - asset: fonts/ArialCoptic.ttf

